export default [
    {
        id: 1,
        imageUrl: '/src/assets/images/job-sectors/IT.jpg',
        title: 'IT Field',
        country: 'Malaysia',
        companyName: 'Demo',
        requiredNo: '65',
        minQualification: 'Masters in Realted Field',
        salary: '60,000 to 70,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.',
    },
    {
        id: 2,
        imageUrl: '/src/assets/images/job-sectors/IT.jpg',
        title: 'IT Field',
        country: 'Qatar',
        companyName: 'Demo',
        requiredNo: '50',
        minQualification: 'Masters in Realted Field',
        salary: '80,000 to 90,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 3,
        imageUrl: '/src/assets/images/job-sectors/cleaner.jpg',
        title: 'Cleaning Section',
        country: 'Malaysia',
        companyName: 'Demo',
        requiredNo: '65',
        minQualification: 'Masters in Realted Field',
        salary: '60,000 to 70,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.',
    },
    {
        id: 4,
        imageUrl: '/src/assets/images/job-sectors/cleaner.jpg',
        title: 'Cleaning Section',
        country: 'Qatar',
        companyName: 'Demo',
        requiredNo: '50',
        minQualification: 'Masters in Realted Field',
        salary: '80,000 to 90,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 5,
        imageUrl: '/src/assets/images/job-sectors/mechanics.jpg',
        title: 'Mechanics',
        country: 'Malaysia',
        companyName: 'Demo',
        requiredNo: '65',
        minQualification: 'Masters in Realted Field',
        salary: '60,000 to 70,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.',
    },
    {
        id: 6,
        imageUrl: '/src/assets/images/job-sectors/mechanics.jpg',
        title: 'Mechanics',
        country: 'Qatar',
        companyName: 'Demo',
        requiredNo: '50',
        minQualification: 'Masters in Realted Field',
        salary: '80,000 to 90,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 7,
        imageUrl: '/src/assets/images/job-sectors/office-staff.webp',
        title: 'Office Staff',
        country: 'Malaysia',
        companyName: 'Demo',
        requiredNo: '65',
        minQualification: 'Masters in Realted Field',
        salary: '60,000 to 70,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.',
    },
    {
        id: 8,
        imageUrl: '/src/assets/images/job-sectors/office-staff.webp',
        title: 'Office Staff',
        country: 'Qatar',
        companyName: 'Demo',
        requiredNo: '50',
        minQualification: 'Masters in Realted Field',
        salary: '80,000 to 90,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.',
    },
    {
        id: 9,
        imageUrl: '/src/assets/images/job-sectors/medical.webp',
        title: 'Medical & Health',
        country: 'Malaysia',
        companyName: 'Demo',
        requiredNo: '65',
        minQualification: 'Masters in Realted Field',
        salary: '60,000 to 70,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.',
    },
    {
        id: 10,
        imageUrl: '/src/assets/images/job-sectors/medical.webp',
        title: 'Medical & Health',
        country: 'Qatar',
        companyName: 'Demo',
        requiredNo: '50',
        minQualification: 'Masters in Realted Field',
        salary: '80,000 to 90,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 11,
        imageUrl: '/src/assets/images/job-sectors/sales.webp',
        title: 'Sales Service',
        country: 'Malaysia',
        companyName: 'Demo',
        requiredNo: '65',
        minQualification: 'Masters in Realted Field',
        salary: '60,000 to 70,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 12,
        imageUrl: '/src/assets/images/job-sectors/sales.webp',
        title: 'Sales Service',
        country: 'Qatar',
        companyName: 'Demo',
        requiredNo: '50',
        minQualification: 'Masters in Realted Field',
        salary: '80,000 to 90,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 13,
        imageUrl: '/src/assets/images/job-sectors/watchman.avif',
        title: 'Watchman',
        country: 'Malaysia',
        companyName: 'Demo',
        requiredNo: '65',
        minQualification: 'Masters in Realted Field',
        salary: '60,000 to 70,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.',
    },
    {
        id: 14,
        imageUrl: '/src/assets/images/job-sectors/watchman.avif',
        title: 'Watchman',
        country: 'Qatar',
        companyName: 'Demo',
        requiredNo: '50',
        minQualification: 'Masters in Realted Field',
        salary: '80,000 to 90,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 15,
        imageUrl: '/src/assets/images/job-sectors/manufacturer.webp',
        title: 'Manufacturer',
        country: 'Malaysia',
        companyName: 'Demo',
        requiredNo: '65',
        minQualification: 'Masters in Realted Field',
        salary: '60,000 to 70,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 16,
        imageUrl: '/src/assets/images/job-sectors/manufacturer.webp',
        title: 'Manufacturer',
        country: 'Qatar',
        companyName: 'Demo',
        requiredNo: '50',
        minQualification: 'Masters in Realted Field',
        salary: '80,000 to 90,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 17,
        imageUrl: '/src/assets/images/job-sectors/construction.webp',
        title: 'Construction',
        country: 'Malaysia',
        companyName: 'Demo',
        requiredNo: '65',
        minQualification: 'Masters in Realted Field',
        salary: '60,000 to 70,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
    {
        id: 18,
        imageUrl: '/src/assets/images/job-sectors/construction.webp',
        title: 'Construction',
        country: 'Qatar',
        companyName: 'Demo',
        requiredNo: '50',
        minQualification: 'Masters in Realted Field',
        salary: '80,000 to 90,000',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam facere adipisci, perferendis sint nobis tempore. Vel temporibus et nobis illo.'
    },
]